# Author: Tristan-BS
name: Check Submodules for Updates

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'
    
  workflow_dispatch:

env:
  REPO_NAME: Updated-Submodules
  GITHUB_TOKEN: ${{ secrets.SubChangeTrackerToken }}
  AUTHOR: Tristan-BS
  

jobs:
  SubChangeTracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ env.GITHUB_TOKEN }}

      - name: Update main branch
        run: |
          git checkout main
          git pull origin main

      - name: Create or update the created branch
        run: |
          git checkout -B ${{ env.REPO_NAME }}
          git merge main --no-edit

      - name: Update submodules
        run: |
          git submodule foreach '
            git fetch origin
            git checkout origin/main || git checkout -b origin/main
            git pull
          '

      - name: Check for changes in submodules
        run: |
          git submodule update --remote --merge
          git add .

          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git config --global user.name "${{ github.actor }}"
            git commit -m "Update submodules to latest version"
            git push origin ${{ env.REPO_NAME }} --force
          else
            echo "No changes in submodules"
          fi
# Author: Tristan-BS
